emp_profile/urls.py
from django.urls import path, include
from . import views

app_name = 'emp_profile'

urlpatterns = [
    path('', views.index, name='home'),
    path('display/', views.display, name='display'),
    # path('date_of_retirement/', views.calculate_date_of_retirement, name='date_of_retirement'),
]

employee/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('emp_profile.urls'))
]

emp_profile/models.py
from django.db import models


# Create your models here.
class EmployeeProfile(models.Model):
    # SALUTATION CHOICES
    MR = 'MR'
    MRS = 'MRS'
    MISS = 'MISS'

    SALUTATION_CHOICES = [
        (MR, 'Mr'),
        (MRS, 'Mrs'),
        (MISS, 'Miss'),
    ]

    # HIGHEST QUALIFICATION CHOICES
    BTECH = "BTECH"
    MTECH = "MTECH"
    BSC = "BSC"
    MSC = "MSC"
    MBA = "MBA"
    BBA = "BBA"

    HIGHEST_QUALIFICATION_CHOICES = [
        (BTECH, 'BTech'),
        (MTECH, 'MTech'),
        (BSC, "BSc"),
        (MSC, "MSc"),
        (MBA, "MBA"),
        (BBA, "BBA")
    ]

    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    date_of_birth = models.DateField()
    date_of_joining = models.DateField()
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    zip_code = models.CharField(max_length=6)
    email = models.EmailField()
    marital_status = models.BooleanField(default=False)
    salutation = models.CharField(max_length=4, choices=SALUTATION_CHOICES, default=MR)
    highest_qualification = models.CharField(max_length=5, choices=HIGHEST_QUALIFICATION_CHOICES)


class EmployeePlans(models.Model):
    date_of_retirement = models.DateField()

emp_profile/forms.py
from django import forms
from .models import EmployeeProfile


# Create your views here.
class EmployeeProfileForm(forms.ModelForm):
    date_of_birth = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'type': 'date',

            })
    )
    date_of_joining = forms.DateField(
        widget=forms.DateInput(attrs={
            'type': 'date',

        })
    )

    # date_of_retirement = forms.DateField(
    #     widget=forms.DateInput(attrs={
    #         'type': 'date',
    #     })
    # )

    class Meta:
        model = EmployeeProfile
        fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_joining', 'address',
                  'city', 'state', 'zip_code', 'email', 'marital_status', 'salutation', 'highest_qualification']

emp_profile/views.py
from django.shortcuts import render, redirect
from .forms import EmployeeProfileForm
from django.http import HttpResponse
from .models import EmployeeProfile, EmployeePlans
# calculating age
from datetime import date
from datetime import datetime


def calculate_age(date_of_birth):
    today = date.today()
    age = today.year - date_of_birth.year - ((today.month, today.day) < (date_of_birth.month, date_of_birth.day))
    return age


def calculate_date_of_retirement():
    dob_list = list(EmployeeProfile.objects.values('date_of_birth'))
    # dob_list = dob_list
    print("DOB", dob_list)

    for x in dob_list:
        dob = str(x['date_of_birth'])
        print(x['date_of_birth'])
        date_object = datetime.strptime(dob, '%Y-%m-%d').date()
        print('Date Object', date_object)

        print('Date Object Year:', date_object.year)
        year = date_object.year

        print('Date Object month:', date_object.month)
        month = date_object.month

        print('Date Object day:', date_object.day)
        day = date_object.day

        retirement_date = dob.replace(str(date_object.year), str(date_object.year + 58))
        print("Retirement Date:", retirement_date)
        # EmployeePlans(date_of_retirement=retirement_date).save()

    return retirement_date


#
# print(calculate_age(date(1995, 4, 4)), "years")


# Create your views here.
def index(request):
    form = EmployeeProfileForm()
    if request.method == 'POST':
        form = EmployeeProfileForm(request.POST)
        date_of_birth = request.POST.get('date_of_birth')
        date_of_joining = request.POST.get('date_of_joining')
        # date_of_retirement = request.POST.get('date_of_retirement')

        print("DOB", date_of_birth)
        dob = date_of_birth
        date_object = datetime.strptime(dob, '%Y-%m-%d').date()
        print('Date Object', date_object)

        print('Date Object Year:', date_object.year)
        year = date_object.year

        print('Date Object month:', date_object.month)
        month = date_object.month

        print('Date Object day:', date_object.day)
        day = date_object.day

        age = calculate_age(date(year, month, day))
        print("AGE:", age)
        # print("FORM:", form)
        if (age >= 21 and age < 58):
            try:
                print("Try Form:", form)
                form.is_valid()
                form.save()
                return redirect('emp_profile:display')
            except Exception as e:
                return HttpResponse(f'{e} <h1> Invalid Form</h1>')
        else:
            return HttpResponse('Age.')

    return render(request, 'index.html', context={'form': form})


def display(request):
    employees = EmployeeProfile.objects.all().order_by('date_of_joining')
    print(calculate_date_of_retirement())
    retirements_of_employees = calculate_date_of_retirement()
    context = {'employees': employees, 'retirements_of_employees': retirements_of_employees}

    return render(request, 'display.html', context=context)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body style="font-family: 'Bahnschrift'">

<h1 class="text-center">Employee Details
    {% block title %}

    {% endblock %}

</h1>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/display.html
{% extends 'base.html' %}
{% block title %}
    <a href="{% url 'emp_profile:home' %}" class="btn btn-info text-white">
        Home
    </a>
{% endblock %}
{% block content %}

    <table class="table table-striped table-bordered table-hover">

        <thead>
        <tr>
            <th>S.no</th>
            <th>  Name</th>
            <th bgcolor="green" class="text-white">Date of Birth</th>
            <th>Date of Joining</th>
            <th bgcolor="red" class="text-white">Date of Retirement</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Zip Code</th>
            <th>Email</th>
            <th>Marital Status</th>
            <th>Salutation</th>
            <th>Highest Qualification</th>
        </tr>
        </thead>
        {% for employee in employees %}

            <tr>
                <td>
                    {{ forloop.counter }}
                </td>

                <td>
                    {{ employee.first_name }}  {{ employee.last_name }}
                </td>



                <td bgcolor="green" class="text-white">
                    {{ employee.date_of_birth }}
                </td>

                <td>
                    {{ employee.date_of_joining }}
                </td>

                <td bgcolor="red" class="text-white">
                    {{ retirements_of_employees }}
                </td>

                <td>
                    {{ employee.address }}
                </td>

                <td>
                    {{ employee.city }}
                </td>

                <td>
                    {{ employee.state }}
                </td>

                <td>
                    {{ employee.zip_code }}
                </td>
                <td>
                    {{ employee.email }}
                </td>
                <td>
                    {{ employee.marital_status }}
                </td>
                <td>
                    {{ employee.salutation }}
                </td>
                <td>
                    {{ employee.highest_qualification }}
                </td>

            </tr>
        {% endfor %}

    </table>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    <a href="{% url 'emp_profile:display' %}" class="btn btn-info text-white">
        View Data
    </a>
{% endblock %}
{% block content %}
    <div class="card">
        <div class="card-body">
            <form method="post">
                <legend class="mb-5 text-center">Employee Details</legend>
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.first_name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.last_name|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.date_of_birth|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.date_of_joining|as_crispy_field }}
                    </div>

                    {#                    <div class="form-group col-md-4 mb-0">#}
                    {#                        {{ form.date_of_retirement|as_crispy_field }}#}
                    {#                    </div>#}


                </div>
                <div class="form-row">
                    <div class="form-group col-md-12 mb-0">
                        {{ form.address|as_crispy_field }}
                    </div>

                </div>
                <div class="form-row">
                    <div class="form-group col-md-3 mb-0">
                        {{ form.city|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-3 mb-0">
                        {{ form.state|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-3 mb-0">
                        {{ form.zip_code|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-3 mb-0">
                        {{ form.email|as_crispy_field }}
                    </div>
                </div>

                {{ form.marital_status|as_crispy_field }}

                <div class="form-row">

                    <div class="form-group col-md-3 mb-0">
                        {{ form.salutation|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-3 mb-0">
                        {{ form.highest_qualification|as_crispy_field }}
                    </div>

                </div>

                <div class="form-row">
                    <div class="form-group col-md-3 mb-0">
                        <input type="submit" class="btn btn-primary" value="Save">
                        <input type="reset" class="btn btn-danger" value="Reset">
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}